### ISSUE TITLE
[ISSUE]: Pipeline is not initialized.

### ISSUE THREAD

**Issue by kueniyo** [w-okada/voice-changer#1087]
### Voice Changer Version

MMVCServerSIO_win_onnxgpu-cuda_v.1.5.3.15.zip

### Operational System

windows 10

### GPU

650 Ti

### Read carefully and check the options

- [ ] I've tried to Clear Settings
- [X] Sample/Default Models are working
- [X] I've tried to change the Chunk Size
- [X] GUI was successfully launched
- [X] I've read the [tutorial](https://github.com/w-okada/voice-changer/blob/master/tutorials/tutorial_rvc_en_latest.md)
- [ ] I've tried to extract to another folder (or re-extract) the .zip file

### Model Type

RVC

### Issue Description

I ran the program and set it up properly.
The moment you press Start, the two sentence log appears repeatedly and the voice changer does not work.

[Voice Changer] Pipeline is not initialized.
[Voice Changer] Waiting generate pipeline...

I've also tried using v.1.5.3.17b and v.1.5.3.17, but I get the same problem.

Please help me solve the problem and use it.

### Application Screenshot

![image](https://github.com/w-okada/voice-changer/assets/103963581/89f6dd60-00e6-4706-ab3f-411260257ed8)
![image](https://github.com/w-okada/voice-changer/assets/103963581/af064276-ddee-4675-b583-9211b66e62fe)

### Logs on console

[Voice Changer] update configuration: modelSlotIndex 1705480782001
[Voice Changer] model slot is changed 0 -> 1
................RVC
[Voice Changer] [RVCr2] Creating instance
VoiceChangerV2 Initialized (GPU_NUM(cuda):1, mps_enabled:False, onnx_device:GPU)
[Voice Changer][RVC]: update_settings gpu:0
[Voice Changer][RVCr2] Initializing...
2024-01-17 17:39:43.6932558 [W:onnxruntime:, session_state.cc:1030 onnxruntime::VerifyEachNodeIsAssignedToAnEp] Some nodes were not assigned to the preferred execution providers which may or may not have an negative impact on performance. e.g. ORT explicitly assigns shape related ops to CPU to improve perf.
2024-01-17 17:39:43.7048334 [W:onnxruntime:, session_state.cc:1032 onnxruntime::VerifyEachNodeIsAssignedToAnEp] Rerunning with verbose output on a non-minimal build will show node assignments.
2024-01-17 17:39:43.7817289 [E:onnxruntime:, inference_session.cc:1500 onnxruntime::InferenceSession::Initialize::<lambda_d67cde18891e9d311739162a2b4aba6d>::operator ()] Exception during initialization: D:\a\_work\1\s\onnxruntime\core\providers\cuda\cuda_call.cc:124 onnxruntime::CudaCall D:\a\_work\1\s\onnxruntime\core\providers\cuda\cuda_call.cc:117 onnxruntime::CudaCall CUBLAS failure 3: CUBLAS_STATUS_ALLOC_FAILED ; GPU=0 ; hostname=DESKTOP-CFIV77F ; expr=cublasCreate(&cublas_handle_);

[Voice Changer] exception! loading inferencer [ONNXRuntimeError] : 6 : RUNTIME_EXCEPTION : Exception during initialization: D:\a\_work\1\s\onnxruntime\core\providers\cuda\cuda_call.cc:124 onnxruntime::CudaCall D:\a\_work\1\s\onnxruntime\core\providers\cuda\cuda_call.cc:117 onnxruntime::CudaCall CUBLAS failure 3: CUBLAS_STATUS_ALLOC_FAILED ; GPU=0 ; hostname=DESKTOP-CFIV77F ; expr=cublasCreate(&cublas_handle_);

Traceback (most recent call last):
  File "voice_changer\RVC\pipeline\PipelineGenerator.py", line 22, in createPipeline
  File "voice_changer\RVC\inferencer\InferencerManager.py", line 25, in getInferencer
  File "voice_changer\RVC\inferencer\InferencerManager.py", line 55, in loadInferencer
  File "voice_changer\RVC\inferencer\OnnxRVCInferencer.py", line 17, in loadModel
  File "onnxruntime\capi\onnxruntime_inference_collection.py", line 347, in __init__
  File "onnxruntime\capi\onnxruntime_inference_collection.py", line 395, in _create_inference_session
onnxruntime.capi.onnxruntime_pybind11_state.RuntimeException: [ONNXRuntimeError] : 6 : RUNTIME_EXCEPTION : Exception during initialization: D:\a\_work\1\s\onnxruntime\core\providers\cuda\cuda_call.cc:124 onnxruntime::CudaCall D:\a\_work\1\s\onnxruntime\core\providers\cuda\cuda_call.cc:117 onnxruntime::CudaCall CUBLAS failure 3: CUBLAS_STATUS_ALLOC_FAILED ; GPU=0 ; hostname=DESKTOP-CFIV77F ; expr=cublasCreate(&cublas_handle_);

[Voice Changer] pipeline create failed. check your model is valid.
[Voice Changer] Pipeline is not initialized.
[Voice Changer] Waiting generate pipeline...
Generated Strengths: for prev:(128,), for cur:(128,)
[Voice Changer] Pipeline is not initialized.
[Voice Changer] Waiting generate pipeline...
[Voice Changer] Pipeline is not initialized.
[Voice Changer] Waiting generate pipeline...
[Voice Changer] Pipeline is not initialized.
[Voice Changer] Waiting generate pipeline...
[Voice Changer] Pipeline is not initialized.
[Voice Changer] Waiting generate pipeline...
[Voice Changer] Pipeline is not initialized.
[Voice Changer] Waiting generate pipeline...
[Voice Changer][RVC]: update_settings f0Detector:rmvpe
[Voice Changer] Pipeline is not initialized.
[Voice Changer] Waiting generate pipeline...
[Voice Changer] Pipeline is not initialized.
[Voice Changer] Waiting generate pipeline...
[Voice Changer] Pipeline is not initialized.
[Voice Changer] Waiting generate pipeline...
[Voice Changer] Pipeline is not initialized.
[Voice Changer] Waiting generate pipeline...
[Voice Changer] Pipeline is not initialized.
[Voice Changer] Waiting generate pipeline...
[Voice Changer][RVC]: update_settings silentThreshold:0.00003
[Voice Changer] Pipeline is not initialized.
[Voice Changer] Waiting generate pipeline...
[Voice Changer] Pipeline is not initialized.
[Voice Changer] Waiting generate pipeline...
[Voice Changer] Pipeline is not initialized.
[Voice Changer] Waiting generate pipeline...
[Voice Changer] Pipeline is not initialized.
[Voice Changer] Waiting generate pipeline...
[Voice Changer][RVC]: update_settings serverReadChunkSize:1
[Voice Changer] Pipeline is not initialized.
[Voice Changer] Waiting generate pipeline...
[Voice Changer] Pipeline is not initialized.
[Voice Changer] Waiting generate pipeline...
[Voice Changer] Pipeline is not initialized.
[Voice Changer] Waiting generate pipeline...
[Voice Changer] Pipeline is not initialized.
[Voice Changer] Waiting generate pipeline...
[Voice Changer] Pipeline is not initialized.
[Voice Changer] Waiting generate pipeline...
[Voice Changer][RVC]: update_settings modelSlotIndex:1705480782001
[Voice Changer] Pipeline is not initialized.
[Voice Changer] Waiting generate pipeline...
[Voice Changer] Pipeline is not initialized.
[Voice Changer] Waiting generate pipeline...
[Voice Changer] Pipeline is not initialized.
[Voice Changer] Waiting generate pipeline...

**Comment by vvirtues** [comment]
Can confirm, audio only plays with passthru enabled

**Comment by vvirtues** [comment]
seems to only affect RVC, the default beatrice included works fine

**Comment by vvirtues** [comment]
This happens after pressing start, and it doesnt make any output at all

**Comment by vvirtues** [comment]
problem is gone using `start_http` and freeing up some memory, will do more testing later
