### ISSUE TITLE
[ISSUE]: Not using AMD GPU at all. tried most things i know

### ISSUE THREAD

**Issue by koko667** [w-okada/voice-changer#1271]
### Voice Changer Version

MMVCServerSIO_win_onnxgpu-cuda_v.1.5.3.18a

### Operational System

Windows 10

### GPU

XFX RX 6800, Ryzen 5 7600 IGPU

### Read carefully and check the options

- [X] I've tried to Clear Settings
- [X] Sample/Default Models are working
- [X] I've tried to change the Chunk Size
- [X] GUI was successfully launched
- [X] I've read the [tutorial](https://github.com/w-okada/voice-changer/blob/master/tutorials/tutorial_rvc_en_latest.md)
- [X] I've tried to extract to another folder (or re-extract) the .zip file

### Model Type

RVC, ONNX

### Issue Description

I have tried all the gpu(dml) options and none of them uses my external gpu seen from task manager and only uses my cpu or igpu when its on gpu0 option, tried reinstalling, trying onnx voice model and everything it just simply doesnt utilize my external gpu

### Application Screenshot

![image](https://github.com/w-okada/voice-changer/assets/175311021/76af059b-2001-483e-a6b1-1e95adc55fd0)
![image](https://github.com/w-okada/voice-changer/assets/175311021/c6a2d179-1a3b-4fd4-8933-f5349a580ecb)

### Logs on console

C:\Users\user\Desktop\MMVCServerSIO>MMVCServerSIO.exe     -p 18888     --https false     --content_vec_500 pretrain/checkpoint_best_legacy_500.pt     --content_vec_500_onnx pretrain/content_vec_500.onnx     --content_vec_500_onnx_on true     --hubert_base pretrain/hubert_base.pt     --hubert_base_jp pretrain/rinna_hubert_base_jp.pt     --hubert_soft pretrain/hubert/hubert-soft-0d54a1f4.pt     --nsf_hifigan pretrain/nsf_hifigan/model     --crepe_onnx_full pretrain/crepe_onnx_full.onnx     --crepe_onnx_tiny pretrain/crepe_onnx_tiny.onnx     --rmvpe pretrain/rmvpe.pt     --model_dir model_dir     --samples samples.json
    Booting PHASE :__main__
    PYTHON:3.10.11 (tags/v3.10.11:7d4cc5a, Apr  5 2023, 00:38:17) [MSC v.1929 64 bit (AMD64)]
    Activating the Voice Changer.
[Voice Changer] download sample catalog. samples_0004_t.json
[Voice Changer] download sample catalog. samples_0004_o.json
[Voice Changer] download sample catalog. samples_0004_d.json
[Voice Changer] model_dir is already exists. skip download samples.
    Internal_Port:18888
    protocol: HTTP
    -- ---- --
    Please open the following URL in your browser.
    http://<IP>:<PORT>/
    In many cases, it will launch when you access any of the following URLs.
    http://127.0.0.1:18888/

[VCClient] Access http://127.0.0.1:18888/
[VCClient] wait web server...0 http://127.0.0.1:18888/
    Booting PHASE :__main__
    Booting PHASE :MMVCServerSIO
[Voice Changer] VoiceChangerManager initializing...
[Voice Changer] model slot is changed -1 -> 4
................RVC
[Voice Changer] [RVCr2] Creating instance
VoiceChangerV2 Initialized (GPU_NUM(cuda):0, mps_enabled:False, onnx_device:CPU-DML)
[Voice Changer][RVC]: update_settings gpu:1
[Voice Changer][RVCr2] Initializing...
gin_channels: 256 self.spk_embed_dim: 109
[Voice Changer] generate new embedder. (no embedder)
[Voice Changer] Loading index...
Try loading... model_dir\4\model.index
GENERATE INFERENCER<voice_changer.RVC.inferencer.RVCInferencerv2.RVCInferencerv2 object at 0x000002305295BFA0>
GENERATE EMBEDDER<voice_changer.RVC.embedder.OnnxContentvec.OnnxContentvec object at 0x00000230AD334940>
GENERATE PITCH EXTRACTOR<voice_changer.RVC.pitchExtractor.RMVPEOnnxPitchExtractor.RMVPEOnnxPitchExtractor object at 0x00000230AD334970>
[Voice Changer] [RVC] Initializing... done
[Voice Changer][RVC]: update_settings f0Detector:rmvpe_onnx
[Voice Changer][RVC]: update_settings serverReadChunkSize:128
[Voice Changer][RVC]: update_settings extraConvertSize:16384
[Voice Changer][RVC]: update_settings silentThreshold:0.001
[Voice Changer][RVC]: update_settings modelSlotIndex:1720695785004
[Voice Changer] VoiceChangerManager initializing... done.
[Voice Changer] MMVC_Rest initializing...
[Voice Changer] MMVC_Rest initializing... done.
[Voice Changer] MMVC_SocketIOApp initializing...
[Voice Changer] MMVC_SocketIOApp initializing... done.
[VCClient] wait web server... done 200
[2024-07-11 19:09:20] connet sid : JPI-MESSuePoULCnAAAC
[2024-07-11 19:09:20] connet sid : 4WngjXAi_jXLHW88AAAD
[Voice Changer] update configuration: tran 2
[Voice Changer][RVC]: update_settings tran:2
[Voice Changer] update configuration: tran 3
[Voice Changer][RVC]: update_settings tran:3
[Voice Changer] update configuration: tran 5
[Voice Changer][RVC]: update_settings tran:5
[Voice Changer] update configuration: tran 6
[Voice Changer] update configuration: tran 7
[Voice Changer][RVC]: update_settings tran:6
[Voice Changer] update configuration: tran 8
[Voice Changer][RVC]: update_settings tran:7
[Voice Changer][RVC]: update_settings tran:8
[Voice Changer] update configuration: tran 9
[Voice Changer] update configuration: tran 10
[Voice Changer][RVC]: update_settings tran:9
[Voice Changer][RVC]: update_settings tran:10
[Voice Changer] update configuration: tran 11
[Voice Changer][RVC]: update_settings tran:11
[Voice Changer] update configuration: tran 12
[Voice Changer][RVC]: update_settings tran:12
[Voice Changer] update configuration: tran 13
[Voice Changer][RVC]: update_settings tran:13
[Voice Changer] update configuration: tran 14
[Voice Changer][RVC]: update_settings tran:14
[Voice Changer] update configuration: tran 13
[Voice Changer][RVC]: update_settings tran:13
[Voice Changer] update configuration: tran 12
[Voice Changer][RVC]: update_settings tran:12
Generated Strengths: for prev:(4096,), for cur:(4096,)
[Voice Changer] warming up... generating sola buffer.
Pipeline has been deleted
[Voice Changer][RVCr2] Initializing...
gin_channels: 256 self.spk_embed_dim: 109
[Voice Changer] generate new embedder. (anyway)
[Voice Changer] Loading index...
Try loading... model_dir\4\model.index
GENERATE INFERENCER<voice_changer.RVC.inferencer.RVCInferencerv2.RVCInferencerv2 object at 0x00000230AD381E40>
GENERATE EMBEDDER<voice_changer.RVC.embedder.OnnxContentvec.OnnxContentvec object at 0x00000230AD3347F0>
GENERATE PITCH EXTRACTOR<voice_changer.RVC.pitchExtractor.RMVPEOnnxPitchExtractor.RMVPEOnnxPitchExtractor object at 0x00000230AD334940>
[Voice Changer] [RVC] Initializing... done
Found no NVIDIA driver on your system. Please check that you have an NVIDIA GPU and installed a driver from http://www.nvidia.com/Download/index.aspx
[Voice Changer] exporting onnx... gpu_id:1 gpu_mem:0
[Voice Changer] Warning!!! onnx export with float32. maybe size is doubled.
gin_channels: 256 self.spk_embed_dim: 109
torch\onnx\utils.py:2033: UserWarning: No names were found for specified dynamic axes of provided input.Automatically generated names will be applied to each dynamic axes of input feats
torch\onnx\utils.py:2033: UserWarning: No names were found for specified dynamic axes of provided input.Automatically generated names will be applied to each dynamic axes of input pitch
torch\onnx\utils.py:2033: UserWarning: No names were found for specified dynamic axes of provided input.Automatically generated names will be applied to each dynamic axes of input pitchf
voice_changer\RVC\inferencer\rvc_models\infer_pack\attentions.py:199: TracerWarning: Converting a tensor to a Python boolean might cause the trace to be incorrect. We can't record the data flow of Python values, so this value will be treated as a constant in the future. This means that the trace might not generalize to other inputs!
voice_changer\RVC\inferencer\rvc_models\infer_pack\attentions.py:244: TracerWarning: Converting a tensor to a Python boolean might cause the trace to be incorrect. We can't record the data flow of Python values, so this value will be treated as a constant in the future. This means that the trace might not generalize to other inputs!
voice_changer\RVC\inferencer\rvc_models\infer_pack\attentions.py:245: TracerWarning: Converting a tensor to a Python boolean might cause the trace to be incorrect. We can't record the data flow of Python values, so this value will be treated as a constant in the future. This means that the trace might not generalize to other inputs!
voice_changer\RVC\inferencer\rvc_models\infer_pack\attentions.py:247: TracerWarning: Converting a tensor to a Python boolean might cause the trace to be incorrect. We can't record the data flow of Python values, so this value will be treated as a constant in the future. This means that the trace might not generalize to other inputs!
torch\onnx\_internal\jit_utils.py:306: UserWarning: Constant folding - Only steps=1 can be constant folded for opset >= 10 onnx::Slice op. Constant folding not applied. (Triggered internally at ..\torch\csrc\jit\passes\onnx\constant_fold.cpp:181.)
torch\onnx\utils.py:689: UserWarning: Constant folding - Only steps=1 can be constant folded for opset >= 10 onnx::Slice op. Constant folding not applied. (Triggered internally at ..\torch\csrc\jit\passes\onnx\constant_fold.cpp:181.)
torch\onnx\utils.py:1186: UserWarning: Constant folding - Only steps=1 can be constant folded for opset >= 10 onnx::Slice op. Constant folding not applied. (Triggered internally at ..\torch\csrc\jit\passes\onnx\constant_fold.cpp:181.)
============= Diagnostic Run torch.onnx.export version 2.0.1+cu118 =============
verbose: False, log level: Level.ERROR
======================= 0 NONE 0 NOTE 0 WARNING 0 ERROR ========================

paramDict {'voiceChangerType': 'RVC', 'slot': 4, 'isSampleMode': False, 'sampleId': None, 'files': [{'name': 'model_simple.onnx', 'kind': 'rvcModel', 'dir': ''}, {'name': 'model.index', 'kind': 'rvcIndex', 'dir': ''}], 'params': {}}
FILE: LoadModelParamFile(name='model_simple.onnx', kind='rvcModel', dir='')
move to C:\Users\user\AppData\Local\Temp\tmph_gmu5fz\upload_dir\model_simple.onnx -> model_dir\4\model_simple.onnx
FILE: LoadModelParamFile(name='model.index', kind='rvcIndex', dir='')
move to C:\Users\user\AppData\Local\Temp\tmph_gmu5fz\upload_dir\model.index -> model_dir\4\model.index
RVC:: slotInfo.modelFile model_simple.onnx
[Voice Changer] ONNX Model: Official v2 like
SlotInfo::: RVCModelSlot(slotIndex=-1, voiceChangerType='RVC', name='model_simple', description='', credit='', termsOfUseUrl='', iconFile='', speakers={0: 'target'}, modelFile='model_simple.onnx', indexFile='model.index', defaultTune=0, defaultIndexRatio=0, defaultProtect=0.5, isONNX=True, modelType='onnxRVC', samplingRate=48000, f0=True, embChannels=768, embOutputLayer=12, useFinalProj=False, deprecated=False, embedder='hubert_base', sampleId='', version='v2.1')
params, LoadModelParams(voiceChangerType='RVC', slot=4, isSampleMode=False, sampleId=None, files=[LoadModelParamFile(name='model_simple.onnx', kind='rvcModel', dir=''), LoadModelParamFile(name='model.index', kind='rvcIndex', dir='')], params={})
[Voice Changer] UPDATE MODEL INFO, {"slot":4,"key":"name","val":"Nazuna"}
SlotInfo::: RVCModelSlot(slotIndex=4, voiceChangerType='RVC', name='Nazuna', description='', credit='', termsOfUseUrl='', iconFile='', speakers={'0': 'target'}, modelFile='model_simple.onnx', indexFile='model.index', defaultTune=0, defaultIndexRatio=0, defaultProtect=0.5, isONNX=True, modelType='onnxRVC', samplingRate=48000, f0=True, embChannels=768, embOutputLayer=12, useFinalProj=False, deprecated=False, embedder='hubert_base', sampleId='', version='v2.1')
[Voice Changer] update configuration: tran 6
[Voice Changer][RVC]: update_settings tran:6
[Voice Changer] update configuration: tran 7
[Voice Changer][RVC]: update_settings tran:7
[Voice Changer] update configuration: tran 8
[Voice Changer][RVC]: update_settings tran:8
[Voice Changer] update configuration: tran 8
[Voice Changer][RVC]: update_settings tran:8
[Voice Changer] update configuration: tran 9
[Voice Changer][RVC]: update_settings tran:9
[Voice Changer] update configuration: tran 9
[Voice Changer][RVC]: update_settings tran:9
[Voice Changer] update configuration: tran 10
[Voice Changer][RVC]: update_settings tran:10
[Voice Changer] update configuration: tran 11
[Voice Changer][RVC]: update_settings tran:11
[Voice Changer] update configuration: tran 12
[Voice Changer][RVC]: update_settings tran:12
[Voice Changer] update configuration: serverReadChunkSize 112
[Voice Changer][RVC]: update_settings serverReadChunkSize:112
[Voice Changer] update configuration: extraConvertSize 8192
[Voice Changer][RVC]: update_settings extraConvertSize:8192

**Comment by koko667** [comment]
> You are using the CUDA version which is for nvidia gpus. Download the ML version for AMD.

my bad i actually tried both of them and they both dont work. ive updated the post

**Comment by lenore-puwawa** [comment]
The log says "No such file or directory: 'model_dir\4\model.pth'."
Please check the contents of the "model_dir\4\" directory to make sure the pth file was uploaded correctly.

**Comment by koko667** [comment]
> The log says "No such file or directory: 'model_dir\4\model.pth'." Please check the contents of the "model_dir\4" directory to make sure the pth file was uploaded correctly.

that is probably because i am using an onnx model because i've read on some other posts to try converting my pth to a onnx model and so i've tried both models and they work, it is just simply not using my gpu for this voice changer

**Comment by Usher5048** [comment]
Bump

**Comment by Kuuko-fokkusugaru** [comment]
> Bump

This is not a forum, don't need to bump issues. They remain open until fixed.
Also download v2 instead and try.

**Comment by Usher5048** [comment]
> This is not a forum, don't need to bump issues. They remain open until fixed. Also download v2 instead and try.

Sorry, still getting used to the Github environment. Issue is solved in the most recent beta, thanks. (vcclient_win_std_2.0.65-beta)
![2024-10-24 09_40_13-Voice Changer Client Demo](https://github.com/user-attachments/assets/e8085a6b-e9f0-4d0b-8a33-3a6e5eb430fd)

**Comment by Kuuko-fokkusugaru** [comment]
Does trying different F0 detection makes a difference in CPU and GPU usage? Could you share a screenshot of the task manager while speaking tps we CPU and GPU usage please? Just make sure that it's while speaking as the software goes into idle mode when no sound is detected.

**Comment by Usher5048** [comment]
Hey, don't have access to my work station right now, but I can assure you that when I was talking my CPU peaked at 98%. While the program was idle (not speaking) the CPU sat around 2-3%.
