### ISSUE TITLE
[ISSUE for v2]: 

### ISSUE THREAD

**Issue by kazumi371** [w-okada/voice-changer#1324]
### Voice Changer Version

vcclient

### Operational System

windows 10

### GPU

none

### CUDA Version

none

### Read carefully and check the options

- [X] If you use win_cuda_torch_cuda edition, setup cuda? [see here](https://onnxruntime.ai/docs/execution-providers/CUDA-ExecutionProvider.html#requirements)
- [X] If you use win_cuda edition, setup cuda and cudnn? [see here](https://onnxruntime.ai/docs/execution-providers/CUDA-ExecutionProvider.html#requirements)
- [X] If you use mac edition, client is not launched automatically. Use chrome to open application.?
- [X] I've tried to change the Chunk Size
- [X] I've tried to set the Index to zero
- [X] I've read the [tutorial](https://github.com/w-okada/voice-changer/blob/master/tutorials/tutorial_rvc_en_latest.md)
- [X] I've tried to extract to another folder (or re-extract) the .zip file

### Does pre-installed model work?

No

### Model Type

rvc

### Issue Description

the colab version is not outputting anything and its not reading inputs

### Application Screenshot

![how do i fix this 3](https://github.com/user-attachments/assets/0873c6e9-37cb-43b3-8ce8-69211a4b2bf1)

### Logs on console

File "vcclient_dev/voice_changer/voice_change_manager/models/rvc/attentions.py", line 52, in forward
File "torch/nn/modules/module.py", line 1553, in _wrapped_call_impl
return self._call_impl(*args, **kwargs)
File "torch/nn/modules/module.py", line 1562, in _call_impl
return forward_call(*args, **kwargs)
File "vcclient_dev/voice_changer/voice_change_manager/models/rvc/attentions.py", line 181, in forward
File "torch/nn/modules/module.py", line 1553, in _wrapped_call_impl
return self._call_impl(*args, **kwargs)
File "torch/nn/modules/module.py", line 1562, in _call_impl
return forward_call(*args, **kwargs)
File "torch/nn/modules/conv.py", line 308, in forward
return self._conv_forward(input, self.weight, self.bias)
File "torch/nn/modules/conv.py", line 304, in _conv_forward
return F.conv1d(input, weight, bias, self.stride,
RuntimeError: CUDNN_BACKEND_TENSOR_DESCRIPTOR cudnnFinalize failed cudnn_status: CUDNN_STATUS_NOT_INITIALIZED
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
File "vcclient_dev/server/validation_error_logging_route.py", line 17, in custom_route_handler
File "fastapi/routing.py", line 278, in app
File "fastapi/routing.py", line 191, in run_endpoint_function
File "vcclient_dev/server/vcserver_rest_api_voice_changaer.py", line 88, in post_convert_chunk
File "vcclient_dev/voice_changer/voice_change_manager/voice_changer.py", line 390, in convert_chunk
File "vcclient_dev/voice_changer/voice_change_manager/voice_changer.py", line 516, in _convert_chunk
File "vcclient_dev/voice_changer/voice_change_manager/vc_pipelines/rvc_pipeline.py", line 320, in run
File "vcclient_dev/voice_changer/voice_change_manager/inferencer/rvc_inverencer_v2_f0.py", line 99, in infer
RuntimeError: ('Exeption in RVCInferencerv2F0', RuntimeError('CUDNN_BACKEND_TENSOR_DESCRIPTOR cudnnFinalize failed cudnn_status: CUDNN_STATUS_NOT_INITIALIZED'))
- vcclient_dev/server/validation_error_logging_route.py - 33
2024-08-21 03:35:13,013 - vcclient - main - INFO - 2024/08/21 03:35:13: running... - vcclient_dev/main.py - 199

**Comment by kazumi371** [comment]
![how do i fix this 4](https://github.com/user-attachments/assets/7f0fbaaa-6501-47ed-9116-92e3a9284773)
my friend keep getting this

**Comment by Kuuko-fokkusugaru** [comment]
Did you pick Tensor gpu from the list? Did you also setup it in Google collab settings?

**Comment by kazumi371** [comment]
> Did you pick Tensor gpu from the list? Did you also setup it in Google collab settings?

Wait the t4 one doesn't work anymore

**Comment by kazumi371** [comment]
If you're talking about the t4 one then yes they said it glitches out specifically when they use that one

**Comment by kazumi371** [comment]
In that error code just keeps showing up

**Comment by kazumi371** [comment]
![Uploading how do i fix this 5.PNG…]()

**Comment by kazumi371** [comment]
![how do i fix this 5](https://github.com/user-attachments/assets/2707cb67-bdfb-44d5-87b3-3ad287667860)

**Comment by Kuuko-fokkusugaru** [comment]
There is a button that may make it easier for you to download the whole log and show the missing parts from the screenshot. I am not a programmer but I am sure that Mr. Okada will probably be able to take a better look.

**Comment by kazumi371** [comment]
ok

**Comment by kazumi371** [comment]
[logs.txt](https://github.com/user-attachments/files/16705602/logs.txt)

**Comment by Kuuko-fokkusugaru** [comment]
I have just tried the colab one and it works perfectly fine with the exception that, after few minutes, it stops working because I am not paying for any of the premium plans, which is expected. Other than that, I managed to use the default models to convert an audio clip in real time. It was a bit choppy at first and the output would cut every second or so but after a while it started to behave correctly, then the server stopped due the free limitations.

**Comment by kazumi371** [comment]
Well it doesn't work specifically for the t4 gpu they mentioned how it works fine with just a normal CPU but it's really slow but for the t4 GPU it shows that error message it's either not reading that GPU being used or it's running an error because there's something wrong with cuda

**Comment by Kuuko-fokkusugaru** [comment]
I used it perfectly fine with the T4 GPU.

**Comment by kazumi371** [comment]
Then I don't know what's going on with theirs

**Comment by Kuuko-fokkusugaru** [comment]
Try a different browser maybe?

**Comment by Kuuko-fokkusugaru** [comment]
I get some errors in the console too but the conversion still works. I can't test deeper because I am free user so I barely can use it for around 5 minutes.

**Comment by kazumi371** [comment]
> I used it perfectly fine with the T4 GPU.

Which link are you choosing to collab proxy or Ngrok URL? And are you using the version that was updated 3 days ago or

**Comment by Kuuko-fokkusugaru** [comment]
I just used the link in the main page of RVC. Then I click on "open in colab" button.
https://github.com/w-okada/voice-changer/blob/v.2/w_okada's_Voice_Changer_version_2_x.ipynb
After that, I just follow the instructions given, enter my Ngrok token, and run it. I open the Ngrok URL that ends in "app" and I am done.

**Comment by kazumi371** [comment]
> I just used the link in the main page of RVC. Then I click on "open in colab" button. https://github.com/w-okada/voice-changer/blob/v.2/w_okada's_Voice_Changer_version_2_x.ipynb After that, I just follow the instructions given, enter my Ngrok token, and run it. I open the Ngrok URL that ends in "app" and I am done.

it still does not work

**Comment by kazumi371** [comment]
[logs (1).txt](https://github.com/user-attachments/files/16738496/logs.1.txt)

**Comment by kazumi371** [comment]
It's sometimes works for them but they keep getting an error message when they speak into the mic and that's the problem it's not outputting anything it just keeps running into that error message something about cuda not finalized and it has something to do with the t4 GPU

**Comment by kazumi371** [comment]
I don't know why it's not working for them

**Comment by kazumi371** [comment]
Cuz sometimes when you open it it's set to CPU and using the CPU it doesn't work for them it's an error within the files or something with a cuda programming or cuda version it's running

**Comment by kazumi371** [comment]
I hope this is helpful for this issue to potentially be fixed

**Comment by kazumi371** [comment]
its still not working for them

**Comment by Kuuko-fokkusugaru** [comment]
> its still not working for them

Are they paying premium service?

**Comment by kazumi371** [comment]
> > its still not working for them
> 
> Are they paying premium service?

No but it usually works without it

**Comment by kazumi371** [comment]
For some reason there's can run for hours

**Comment by Kuuko-fokkusugaru** [comment]
Well now you know why it doesn't work then.
Google stop the processes after few minutes, that's why there is no output sound. It only works for few minutes then you need to wait for hours before being able to try again.

**Comment by kazumi371** [comment]
> Well now you know why it doesn't work then. Google stop the processes after few minutes, that's why there is no output sound. It only works for few minutes then you need to wait for hours before being able to try again.

That doesn't explain the error messages

**Comment by Kuuko-fokkusugaru** [comment]
> > Well now you know why it doesn't work then. Google stop the processes after few minutes, that's why there is no output sound. It only works for few minutes then you need to wait for hours before being able to try again.
> 
> That doesn't explain the error messages something is wrong with a specific file or folder

That doesn't matter. As mentioned already, the software works regardless of the error. I get the error too but the software works and even you stated that it worked at first then stopped working. That's because it will only do for few minutes unless you pay. It won't for for free. And the colab version is the same for everyone since is ran remotely so it either fails for everyone or works for everyone. So, unless something is done wrongly at time of running it, it should still work. You can try running it through a different browser and you will see that after few minutes the software will give an error because the server has simply stopped processing. The UI will remain and you may be even able to click on the buttons but you won't get any output at all. I am not sure what else could be done other than paying for a paid service. @w-okada may check and see about that error, but other users are using the colab version just fine already with the difference that they are paying for it.

**Comment by kazumi371** [comment]
Even if you do use another GPU as long as the cuda version or the pytorch version is invalid to the version of the whole thing is not going to work because some reason for my friend it doesn't work if it has errors per say some file is missing or it's having a GPU error and it only works with CPU and the CPU is terrible

**Comment by Kuuko-fokkusugaru** [comment]
The CUDA version doesn't needs to be 1:1 with the software. And there are several users each with different CUDA versions in their systems who reported the software working fine. So, unless it's a major version change, it should work. Also, you don't need to install python or anything since everything necessary is already within the software. Not sure which issues your friend has but remember that this is the colab version which means that you aren't even running it in your local computer. I am not even sure what your last comment is supposed to mean in regards to colab not working.

**Comment by kazumi371** [comment]
> The CUDA version doesn't needs to be 1:1 with the software. And there are several users each with different CUDA versions in their systems who reported the software working fine. So, unless it's a major version change, it should work. Also, you don't need to install python or anything since everything necessary is already within the software. Not sure which issues your friend has but remember that this is the colab version which means that you aren't even running it in your local computer. I am not even sure what your last comment is supposed to mean in regards to colab not working.

I think I figured it out my friend says they only run into that error when they're using models downloaded from a website it works when they use the default models that are already there but when they try to import their own they run into that error the default models there are V3 versions but the ones they're trying to import our V2

**Comment by Kuuko-fokkusugaru** [comment]
The models included are v2 I believe. I have used the colab version with v2 models and it should work with v1 models. I am not aware of the existence of v3 models. Maybe those models are simply wrong or not correctly uploaded.

I feel like we are trying to look for issues that doesn't exists. It's a fact that you need to pay to be able to use the colab version. So rather than trying to find random problems that no one's else have, let's just stick to the fact that it's still a paid service and that's probably the main reason of why it doesn't work for you.

**Comment by kazumi371** [comment]
> The models included are v2 I believe. I have used the colab version with v2 models and it should work with v1 models. I am not aware of the existence of v3 models. Maybe those models are simply wrong or not correctly uploaded.
> 
> I feel like we are trying to look for issues that doesn't exists. It's a fact that you need to pay to be able to use the colab version. So rather than trying to find random problems that no one's else have, let's just stick to the fact that it's still a paid service and that's probably the main reason of why it doesn't work for you.

Cuz they said it works perfectly fine when you use the models that are basically uploaded with the whole client and everything but when they try to add their own it starts giving them that error message when they speak it has nothing to do with the paid version of collab because the same thing will happen even if they did pay for it

**Comment by Kuuko-fokkusugaru** [comment]
Perhaps, those models are just "wrong"? Are they pth or onnx models? The included ones are just onnx models.

**Comment by kazumi371** [comment]
[LOG_FILE_8003.log](https://github.com/user-attachments/files/18552188/LOG_FILE_8003.log)
