### ISSUE TITLE
[REQUEST]: RTX 5070 Ti (sm_120) CUDA not supported in vcclient_win_cuda_2.1.4-alpha

### ISSUE THREAD

**Issue by AkiYamanote** [w-okada/voice-changer#1603]
### In a few words, describe your idea

Add an option or build that supports PyTorch CUDA for RTX 5000 series (sm_120)

### More information

お世話になっております。
VC Client をいつも便利に利用させていただいています。ありがとうございます。

以下の環境で VC Client を起動した際、CUDA に関する警告が表示され、GPU が利用できない状況が発生しています。

■ 起動時の警告
torch\cuda\__init__.py:287: UserWarning:
NVIDIA GeForce RTX 5070 Ti with CUDA capability sm_120 is not compatible with the current PyTorch installation.
The current PyTorch install supports CUDA capabilities sm_37 sm_50 sm_60 sm_61 sm_70 sm_75 sm_80 sm_86 sm_90 compute_37.

■ 使用バージョン
vcclient_win_cuda_2.1.4-alpha

■ GPU
NVIDIA GeForce RTX 5070 Ti

■ 補足
・同一環境にて vcclient_win_cuda_2.0.78-beta は問題なく動作していました
・原因として、バンドルされている PyTorch の CUDA ビルドが sm_120（RTX 5000 シリーズ）に未対応である可能性が高いと考えています
・PyTorch nightly を利用することで回避できる可能性があることも理解していますが、こちらの環境ではまだ検証できていません
・もし PyTorch nightly 等で動作確認された方がいらっしゃいましたら、情報共有いただけると助かります

2.1.x 系で追加された「バッファの可視化」機能が非常に便利で、ぜひ今後も利用したいと考えています。
将来的に RTX 5000 シリーズ（sm_120）に対応した PyTorch CUDA ビルドを含むリリースや、ビルド選択の余地などをご検討いただけましたら幸いです。

素晴らしいツールを公開・開発していただき、ありがとうございます。
今後の更新も楽しみにしております。

------------------

Hello, and thank you very much for developing VC Client.
I really appreciate this great tool.

When launching VC Client in the environment below, I encounter a CUDA-related warning and the GPU cannot be used.

■ Warning on startup
torch\cuda\__init__.py:287: UserWarning:
NVIDIA GeForce RTX 5070 Ti with CUDA capability sm_120 is not compatible with the current PyTorch installation.
The current PyTorch install supports CUDA capabilities sm_37 sm_50 sm_60 sm_61 sm_70 sm_75 sm_80 sm_86 sm_90 compute_37.

■ Version
vcclient_win_cuda_2.1.4-alpha

■ GPU
NVIDIA GeForce RTX 5070 Ti

■ Notes
- The same system works without issues with vcclient_win_cuda_2.0.78-beta
- I believe this issue is likely caused by the bundled PyTorch CUDA build not supporting sm_120 (RTX 5000 series) yet
- I understand that using PyTorch nightly *might* be a possible workaround, but I have not been able to verify this in my environment
- If anyone has successfully tested this with PyTorch nightly or another workaround, I would really appreciate any shared information

The buffer visualization feature introduced in the 2.1.x series is extremely useful, and I would love to keep using it.
If possible, I would greatly appreciate consideration for future releases that include a PyTorch CUDA build compatible with RTX 5000 series GPUs (sm_120), or an option to select such a build.

Thank you again for your work and for making VC Client available to the community.
I am looking forward to future updates.

**Comment by SiliusJM** [comment]
I also have the same problem because I have the 50 series. I recently bought the 5060 and when I tried to test the program, I encountered the same problem: this graphics card is still not compatible with the versions you mentioned in your comment.
If any specific version has helped you avoid this problem, it would be very helpful so that I can continue using this wonderful program

**Comment by RioShiina47** [comment]
I downloaded [torch-2.7.0+cu128-cp310-cp310-win_amd64.whl](https://download.pytorch.org/whl/cu128/torch-2.7.0%2Bcu128-cp310-cp310-win_amd64.whl), extracted it, and copied the torch folder to replace the one inside main\_internal. This resolved the error: CUDA capability sm_120 is not compatible with the current PyTorch installation.

Reasons for choosing torch-2.7.0+cu128-cp310-cp310:
1.vcclient_win_cuda_2.1.4-alpha originally uses torch-2.7.0+cu118-cp310-cp310.
2.Using a version higher than torch-2.7.0 or cu128 triggers a new ImportError: cannot import name '_cuda_endAllocateCurrentStreamToPool' from 'torch._C'.

I also tried updating torchaudio at the same time, but it failed the validation check due to a version mismatch between torch and torchaudio (even though both were cu128; this might be related to how they are packaged).

In summary, updating only torch is enough to solve the problem.

Optional step:
Copy cublasLt64_12.dll, cublas64_12.dll, cudart64_12.dll, and cufft64_11.dll from the new torch\lib folder to main\_internal, replacing the existing files.

**Comment by AkiYamanote** [comment]
Thank you very much for the helpful advice.
I tried it, and I was able to confirm that it runs in GPU mode without any errors.
This was very helpful — much appreciated!

**Comment by itsdeadfrosty** [comment]
> I downloaded [torch-2.7.0+cu128-cp310-cp310-win_amd64.whl](https://download.pytorch.org/whl/cu128/torch-2.7.0%2Bcu128-cp310-cp310-win_amd64.whl), extracted it, and copied the torch folder to replace the one inside main_internal. This resolved the error: CUDA capability sm_120 is not compatible with the current PyTorch installation.
> 
> Reasons for choosing torch-2.7.0+cu128-cp310-cp310: 1.vcclient_win_cuda_2.1.4-alpha originally uses torch-2.7.0+cu118-cp310-cp310. 2.Using a version higher than torch-2.7.0 or cu128 triggers a new ImportError: cannot import name '_cuda_endAllocateCurrentStreamToPool' from 'torch._C'.
> 
> I also tried updating torchaudio at the same time, but it failed the validation check due to a version mismatch between torch and torchaudio (even though both were cu128; this might be related to how they are packaged).
> 
> In summary, updating only torch is enough to solve the problem.
> 
> Optional step: Copy cublasLt64_12.dll, cublas64_12.dll, cudart64_12.dll, and cufft64_11.dll from the new torch\lib folder to main_internal, replacing the existing files.

omg thank u

**Comment by Matman0008** [comment]
still the same error for me with an RTX 5070...
