### ISSUE TITLE
Not using any GPU, only using CPU and Memory.

### ISSUE THREAD

**Issue by Extra-Time** [w-okada/voice-changer#791]
### Issue Type

Bug Report

### vc client version number

MMVCServerSIO_win_onnxgpu-cuda_v.1.5.3.13.zip

### OS

Windows 10

### GPU

NVIDIA GFORCE RTX 3080

### Clear setting

yes

### Sample model

yes

### Input chunk num

yes

### Wait for a while

The GUI successfully launched.

### read tutorial

yes

### Extract files to a new folder.

yes

### Voice Changer type

RVC

### Model type

pyTorch

### Situation

The w-okoda real time voice changer client kept using CPU, although I set it up as a GPU.

I tried updating, I tried reinstalling, I tried using a different program to help this, I reinstalled the CUDA drivers, I tried everything...

![image](https://github.com/w-okada/voice-changer/assets/92290984/6094e046-2397-44f6-b58c-2dfbbe732c5a)

it still uses CPU.. help

### application window capture

![image](https://github.com/w-okada/voice-changer/assets/92290984/6453c53e-39e4-4d07-9a01-1182d507d8c1)

### logs on terminal

C:\VOICE CHANGER\MMVCServerSIO>MMVCServerSIO.exe     -p 18888     --https false     --content_vec_500 pretrain/checkpoint_best_legacy_500.pt     --content_vec_500_onnx pretrain/content_vec_500.onnx     --content_vec_500_onnx_on true     --hubert_base pretrain/hubert_base.pt     --hubert_base_jp pretrain/rinna_hubert_base_jp.pt     --hubert_soft pretrain/hubert/hubert-soft-0d54a1f4.pt     --nsf_hifigan pretrain/nsf_hifigan/model     --crepe_onnx_full pretrain/crepe_onnx_full.onnx     --crepe_onnx_tiny pretrain/crepe_onnx_tiny.onnx     --rmvpe pretrain/rmvpe.pt     --model_dir model_dir     --samples samples.json
    Booting PHASE :__main__
    PYTHON:3.10.11 (tags/v3.10.11:7d4cc5a, Apr  5 2023, 00:38:17) [MSC v.1929 64 bit (AMD64)]
    Activating the Voice Changer.
[Voice Changer] download sample catalog. samples_0003_t2.json
[Voice Changer] download sample catalog. samples_0003_o2.json
[Voice Changer] download sample catalog. samples_0003_d2.json
[Voice Changer] model_dir is already exists. skip download samples.
    Internal_Port:18888
    protocol: HTTP
    -- ---- --
    Please open the following URL in your browser.
    http://<IP>:<PORT>/
    In many cases, it will launch when you access any of the following URLs.
    http://127.0.0.1:18888/

[VCClient] Access http://127.0.0.1:18888/
[VCClient] wait web server...0 http://127.0.0.1:18888/
    Booting PHASE :__main__
    Booting PHASE :MMVCServerSIO
[Voice Changer] VoiceChangerManager initializing...

**Comment by Extra-Time** [comment]
60.4% on CPU and 0.3% on GPU is crazy

**Comment by w-okada** [comment]
set index to 0.

**Comment by Extra-Time** [comment]
> set index to 0.

I tried, except it's just using less CPU, and still is not using any GPU.

![image-62](https://github.com/w-okada/voice-changer/assets/92290984/5894ff46-4fb7-4d1b-9df9-1808827037b5)
![image-97](https://github.com/w-okada/voice-changer/assets/92290984/fabbca47-3a4a-4881-b578-33706991cb2b)

This is before and after of index. I just don't think using 0.1% ~ 0.5% GPU is possible though??

I honestly don't know.

Thanks for the reply though!

**Comment by Extra-Time** [comment]
+my 'wallpaper engine' is using more GPU than my voice changer 😔😔

**Comment by w-okada** [comment]
set index 0

**Comment by Extra-Time** [comment]
> set index 0

was at 0 already, check this screenshot out
![image](https://github.com/w-okada/voice-changer/assets/92290984/82d453b0-7795-409e-910b-7524a576482c)

**Comment by ralyx** [comment]
I have amd graphics card but i had the same issue i solved it by exporting the custom voice to onnx ,uploading it to the slot and then switching to another character and then to that character again.And if it doesn't work you try every extra and chunk combination.I don't actually have a lot of knowledge but it's worth trying.And i also changed a setting in advanced settings.I changed a value from 100 to 300 hope it works for you ;).

**Comment by Extra-Time** [comment]
> 

I tried voice onnx feature, and it didnt work.. also advanced setting one was at 300 at all costs :) thanks tho

**Comment by w-okada** [comment]
https://platform.openai.com/playground/p/rboN8tB3w6ovpjuzf5Vzaepx

**Comment by w-okada** [comment]
Does the same phenomenon occur with the sample model too?

**Comment by w-okada** [comment]
no res close
